### PR TITLE
First attempt at adding a test for cairosvg

### PR DESCRIPTION
**Pull request by pharshalp**
attempts to address  #17. This is my first PR dealing with a test in conda-forge recipe. I would appreciate any guidance/help.
@conda-forge-admin, please rerender

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by carlodri** [comment]
thanks @pharshalp! I'm a little busy these days, I will try to take a look as soon as I can.

**Review by carlodri — CHANGES_REQUESTED** [review]
thanks @pharshalp! I think we can improve this in some ways:

* also for test data files, you should possibly rely on downloadable resources (_e.g._ https://github.com/Kozea/CairoSVG/tree/master/test_non_regression/images)

* if you need to bring files in the testing area, you need to bring them in as shown [here](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#test-section)

Let me know if I can help further! I would like to get this PR merged before #20 . Thanks a lot!

**Comment by pharshalp** [comment]
Thanks for the feedback to improve this PR. I plan to work on this on the upcoming weekend.

**Comment by carlodri** [comment]
@pharshalp friendly ping! 😉

**Comment by pharshalp** [comment]
@carlodri Thanks for the friendly reminder... working on it now... will submit an update in a few minutes.

**Comment by pharshalp** [comment]
@carlodri I think this is ready for review. The test.svg file that I am using can be viewed here:
https://github.com/conda-forge/cairosvg-feedstock/blob/6e561d877503b8f63372a407dc580b300ef811cb/recipe/test.svg

The reason I chose this file is that it contains text elements which failed to convert when using cairosvg 2.3.0 (conda-forge) on Windows.

**Comment by carlodri** [comment]
@pharshalp thanks! As I said, it would be desirable to have a test svg file from the official repo without adding a custom file to the feedstock.

Is it possible to choose one or more files from https://github.com/Kozea/CairoSVG/tree/master/test_non_regression/svg or https://github.com/Kozea/CairoSVG/tree/master/test_non_regression/images

For instance https://github.com/Kozea/CairoSVG/blob/master/test_non_regression/svg/text-tspan-01-b.svg also contains text elements.

**Comment by MutantPlatypus** [comment]
Hi @pharshalp, /test_non_regression/svg/toap04.svg seems to give the same error as your test file on my Windows system.

[2.3.0_build_log.txt](https://github.com/conda-forge/cairosvg-feedstock/files/3668570/2.3.0_build_log.txt)
[2.3.0_build_log_err.txt](https://github.com/conda-forge/cairosvg-feedstock/files/3668571/2.3.0_build_log_err.txt)
[2.3.0_build_log_toap04.txt](https://github.com/conda-forge/cairosvg-feedstock/files/3668572/2.3.0_build_log_toap04.txt)
[2.3.0_build_log_toap04_err.txt](https://github.com/conda-forge/cairosvg-feedstock/files/3668573/2.3.0_build_log_toap04_err.txt)

It seems to be related to how the SVG links back to an ID it defined internally.

**Comment by pharshalp** [comment]
I am closing this PR as #26 seems to be handling the suggestions in a better way (and doing a thorough job).  Thanks @MutantPlatypus and @carlodri.

**Comment by carlodri** [comment]
Thanks to you @pharshalp!

**Pull request closed without merging**
